import { CanonicalIntermediateRepresentation } from '../cir';
import { KnowledgeGeneratorPlugin, GeneratorOutputArtifact } from './plugin.interface';

export const testGeneratorPlugin: KnowledgeGeneratorPlugin = {
  id: 'gen-vitest-contract-tests',
  name: 'Vitest Contract Test Skeletons Generator',
  language: 'TypeScript / Vitest',
  version: '1.0.0',
  supportsCirVersion: '1.2.0',

  generate(cir: CanonicalIntermediateRepresentation): GeneratorOutputArtifact {
    let output = `/**\n * AUTO-GENERATED BY PTX KNOWLEDGE COMPILER (PROGRAM A - EO-001)\n * DO NOT MODIFY MANUALLY. SOURCE: PTX FOUNDATION KNOWLEDGE OBJECTS\n * GENERATED AT: ${cir.compiledAt}\n */\n\nimport { describe, it, expect } from 'vitest';\n\n`;

    output += `describe('PTX Knowledge Contract Verification Test Suite', () => {\n`;

    for (const contract of cir.contracts) {
      output += `  describe('Contract ${contract.id}: ${contract.path}', () => {\n`;
      output += `    it('should validate request payload against ${contract.requestSchemaName}', () => {\n`;
      output += `      expect(true).toBe(true);\n`;
      output += `    });\n\n`;
      output += `    it('should wrap response in ${contract.responseSchemaName}', () => {\n`;
      output += `      expect(true).toBe(true);\n`;
      output += `    });\n`;
      output += `  });\n\n`;
    }

    output += `});\n`;

    return {
      name: 'Contract Test Skeletons',
      targetSubDir: 'tests',
      filename: 'contract-tests.ts',
      content: output,
      generatorId: 'gen-vitest-contract-tests',
      generatorVersion: '1.0.0',
      cirVersion: cir.cirSchemaVersion
    };
  }
};
