import { CanonicalIntermediateRepresentation } from '../cir';
import { KnowledgeGeneratorPlugin, GeneratorOutputArtifact } from './plugin.interface';

export const sqlGeneratorPlugin: KnowledgeGeneratorPlugin = {
  id: 'gen-postgresql-schema',
  name: 'PostgreSQL DDL SQL Generator',
  language: 'SQL / PostgreSQL',
  version: '1.0.0',
  supportsCirVersion: '1.2.0',

  generate(cir: CanonicalIntermediateRepresentation): GeneratorOutputArtifact {
    let output = `-- ============================================================================\n`;
    output += `-- AUTO-GENERATED BY PTX KNOWLEDGE COMPILER (PROGRAM A - EO-001)\n`;
    output += `-- DO NOT MODIFY MANUALLY. SOURCE: PTX FOUNDATION KNOWLEDGE OBJECTS\n`;
    output += `-- GENERATED AT: ${cir.compiledAt}\n`;
    output += `-- ============================================================================\n\n`;

    for (const entity of cir.entities) {
      output += `CREATE TABLE IF NOT EXISTS public.${entity.name} (\n`;
      const fieldDefs: string[] = [];
      for (const field of entity.fields) {
        let def = `  ${field.name} ${field.type.toUpperCase()}`;
        if (field.isPrimaryKey) def += ` PRIMARY KEY`;
        if (!field.isNullable && !field.isPrimaryKey) def += ` NOT NULL`;
        if (field.foreignKeyRef) {
          const [refTable, refCol] = field.foreignKeyRef.split('.');
          def += ` REFERENCES public.${refTable}(${refCol}) ON DELETE CASCADE`;
        }
        fieldDefs.push(def);
      }
      output += fieldDefs.join(',\n');
      output += `\n);\n\n`;
    }

    output += `-- ============================================================================\n`;
    output += `-- ATOMIC RPC FUNCTION: fn_add_goal (ADR-001 ATOMIC TRANSACTION)\n`;
    output += `-- ============================================================================\n`;
    output += `CREATE OR REPLACE FUNCTION public.fn_add_goal(\n`;
    output += `  p_match_id UUID,\n  p_team_id UUID,\n  p_player_id UUID,\n  p_minute INT,\n  p_goal_type VARCHAR(50)\n`;
    output += `)\nRETURNS JSONB\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\n`;
    output += `DECLARE\n  v_home_id UUID;\n  v_away_id UUID;\n  v_event_id UUID := gen_random_uuid();\n`;
    output += `BEGIN\n`;
    output += `  -- 1. Verify match is live\n`;
    output += `  SELECT home_team_id, away_team_id INTO v_home_id, v_away_id FROM public.matches WHERE id = p_match_id AND status LIKE 'LIVE_%';\n`;
    output += `  IF NOT FOUND THEN\n    RAISE EXCEPTION 'ERR_MATCH_NOT_LIVE: Match % is not in a live state.', p_match_id;\n  END IF;\n\n`;
    output += `  -- 2. Insert match_event\n`;
    output += `  INSERT INTO public.match_events(id, match_id, event_type, player_id, minute, details_json)\n`;
    output += `  VALUES (v_event_id, p_match_id, 'MATCH_GOAL_ADDED', p_player_id, p_minute, jsonb_build_object('goal_type', p_goal_type, 'team_id', p_team_id));\n\n`;
    output += `  -- 3. Update score atomically\n`;
    output += `  IF p_team_id = v_home_id THEN\n`;
    output += `    UPDATE public.matches SET home_score = home_score + 1 WHERE id = p_match_id;\n`;
    output += `  ELSE\n`;
    output += `    UPDATE public.matches SET away_score = away_score + 1 WHERE id = p_match_id;\n`;
    output += `  END IF;\n\n`;
    output += `  RETURN jsonb_build_object('success', true, 'event_id', v_event_id);\n`;
    output += `END;\n$$;\n`;

    return {
      name: 'PostgreSQL DDL & RPC SQL',
      targetSubDir: 'db',
      filename: 'schema-v1.0.7.sql',
      content: output,
      generatorId: 'gen-postgresql-schema',
      generatorVersion: '1.0.0',
      cirVersion: cir.cirSchemaVersion
    };
  }
};
