import { CanonicalIntermediateRepresentation } from '../cir';
import { KnowledgeGeneratorPlugin, GeneratorOutputArtifact } from './plugin.interface';

export const typescriptGeneratorPlugin: KnowledgeGeneratorPlugin = {
  id: 'gen-typescript-models',
  name: 'TypeScript Domain Models Generator',
  language: 'TypeScript',
  version: '1.0.0',
  supportsCirVersion: '1.2.0',

  generate(cir: CanonicalIntermediateRepresentation): GeneratorOutputArtifact {
    let output = `/**\n * AUTO-GENERATED BY PTX KNOWLEDGE COMPILER (PROGRAM A - EO-001)\n * DO NOT MODIFY MANUALLY. SOURCE: PTX FOUNDATION KNOWLEDGE OBJECTS\n * GENERATED AT: ${cir.compiledAt}\n */\n\n`;

    output += `// ==========================================\n// DOMAIN CAPABILITIES REGISTRY\n// ==========================================\n`;
    output += `export enum DomainCapabilityId {\n`;
    for (const cap of cir.capabilities) {
      const enumKey = cap.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
      output += `  ${enumKey} = '${cap.id}',\n`;
    }
    output += `}\n\n`;

    output += `// ==========================================\n// DOMAIN EVENT TYPES\n// ==========================================\n`;
    for (const event of cir.events) {
      output += `export interface ${pascalCase(event.name)}Payload {\n`;
      for (const field of event.payloadFields) {
        output += `  ${field.name}${field.required ? '' : '?'}: ${mapTypeToTs(field.type)};\n`;
      }
      output += `}\n\n`;
    }

    output += `// ==========================================\n// DATABASE ENTITY DOMAIN MODELS\n// ==========================================\n`;
    for (const entity of cir.entities) {
      output += `export interface ${pascalCase(entity.name.slice(0, -1))} {\n`;
      for (const field of entity.fields) {
        output += `  ${field.name}${field.isNullable ? '?' : ''}: ${mapTypeToTs(field.type)};\n`;
      }
      output += `}\n\n`;
    }

    return {
      name: 'TypeScript Domain Models',
      targetSubDir: 'types',
      filename: 'domain-models.ts',
      content: output,
      generatorId: 'gen-typescript-models',
      generatorVersion: '1.0.0',
      cirVersion: cir.cirSchemaVersion
    };
  }
};

function pascalCase(str: string): string {
  return str
    .toLowerCase()
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

function mapTypeToTs(typeStr: string): string {
  if (typeStr.includes('varchar') || typeStr.includes('text') || typeStr === 'uuid' || typeStr === 'string' || typeStr.includes('timestamp')) {
    return 'string';
  }
  if (typeStr === 'integer' || typeStr === 'number' || typeStr === 'float') {
    return 'number';
  }
  if (typeStr === 'boolean') {
    return 'boolean';
  }
  if (typeStr === 'jsonb' || typeStr === 'object') {
    return 'Record<string, any>';
  }
  return 'any';
}
