import { CanonicalIntermediateRepresentation } from '../cir';
import { KnowledgeGeneratorPlugin, GeneratorOutputArtifact } from './plugin.interface';

export const zodGeneratorPlugin: KnowledgeGeneratorPlugin = {
  id: 'gen-zod-contracts',
  name: 'Zod Validation Contracts Generator',
  language: 'TypeScript / Zod',
  version: '1.0.0',
  supportsCirVersion: '1.2.0',

  generate(cir: CanonicalIntermediateRepresentation): GeneratorOutputArtifact {
    let output = `/**\n * AUTO-GENERATED BY PTX KNOWLEDGE COMPILER (PROGRAM A - EO-001)\n * DO NOT MODIFY MANUALLY. SOURCE: PTX FOUNDATION KNOWLEDGE OBJECTS\n * GENERATED AT: ${cir.compiledAt}\n */\n\nimport { z } from 'zod';\n\n`;

    output += `// ==========================================\n// RESPONSE ENVELOPE CONTRACT SCHEMAS\n// ==========================================\n`;
    output += `export const ApiResponseEnvelopeSchema = <T extends z.ZodTypeAny>(dataSchema: T) =>\n  z.object({\n    success: z.boolean(),\n    data: dataSchema,\n    meta: z.record(z.any()).optional(),\n    timestamp: z.string()\n  });\n\n`;

    output += `// ==========================================\n// API CONTRACT VALIDATION SCHEMAS\n// ==========================================\n`;

    output += `export const AddGoalContractSchema = z.object({\n`;
    output += `  match_id: z.string().uuid({ message: 'match_id phải là định dạng UUID hợp lệ.' }),\n`;
    output += `  team_id: z.string().uuid({ message: 'team_id phải là định dạng UUID hợp lệ.' }),\n`;
    output += `  player_id: z.string().uuid({ message: 'player_id phải là định dạng UUID hợp lệ.' }),\n`;
    output += `  minute: z.number().int().min(1).max(120),\n`;
    output += `  goal_type: z.enum(['NORMAL', 'PENALTY', 'FREE_KICK', 'OWN_GOAL'])\n`;
    output += `});\n\nexport type AddGoalContractInput = z.infer<typeof AddGoalContractSchema>;\n\n`;

    output += `export const GenerateFixturesContractSchema = z.object({\n`;
    output += `  season_id: z.string().uuid({ message: 'season_id phải là định dạng UUID hợp lệ.' }),\n`;
    output += `  format_type: z.enum(['ROUND_ROBIN', 'KNOCKOUT', 'GROUPS'])\n`;
    output += `});\n\nexport type GenerateFixturesContractInput = z.infer<typeof GenerateFixturesContractSchema>;\n\n`;

    output += `export const AddPlayerContractSchema = z.object({\n`;
    output += `  team_id: z.string().uuid({ message: 'team_id phải là định dạng UUID hợp lệ.' }),\n`;
    output += `  name: z.string().min(2).max(100),\n`;
    output += `  shirt_number: z.number().int().min(1).max(99),\n`;
    output += `  position: z.enum(['GK', 'FIXO', 'ALA', 'PIVOT'])\n`;
    output += `});\n\nexport type AddPlayerContractInput = z.infer<typeof AddPlayerContractSchema>;\n\n`;

    return {
      name: 'Zod Contracts',
      targetSubDir: 'contracts',
      filename: 'zod-schemas.ts',
      content: output,
      generatorId: 'gen-zod-contracts',
      generatorVersion: '1.0.0',
      cirVersion: cir.cirSchemaVersion
    };
  }
};
